presence_index:
    path:     /
    defaults: { _controller: "EmployeeBundle:Presence:index" }
    methods:  GET
presence_index_current:
    path:     /current
    defaults: { _controller: "EmployeeBundle:Presence:indexCurrent" }
    methods:  GET

presence_show:
    path:     /{idPresence}/show
    defaults: { _controller: "EmployeeBundle:Presence:show" }
    methods:  GET

presence_new:
    path:     /new
    defaults: { _controller: "EmployeeBundle:Presence:new" }
    methods:  [GET, POST]



presence_fill_A:
    path:     /{idPresence}/editA
    defaults: { _controller: "EmployeeBundle:Presence:editA" }
    methods:  [GET, POST]
    options:
            expose: true

presence_fill_P:
    path:     /{idPresence}/editP
    defaults: { _controller: "EmployeeBundle:Presence:editP" }
    methods:  [GET, POST]
    options:
            expose: true
presence_delete:
    path:     /{idPresence}/delete
    defaults: { _controller: "EmployeeBundle:Presence:delete" }
    methods:  DELETE

presence_newSheet:
    path:     /newpsheet
    defaults: { _controller: "EmployeeBundle:Presence:newPresenceSheet" }
    methods:  GET